### ISSUE TITLE
getBounds()

### ISSUE THREAD

**Issue by ClydSpyd** [google-map-react/google-map-react-examples#22]
Hello.

Is there any way to call the map.getBounds() function? I need to reset the bounds of a nearbySearch upon manually re-centering and can't seem to figure out how to do so.

Cheers,
Dave

**Comment by itsmichaeldiego** [comment]
Yes, you can do it after api has loaded, check here: https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L40

**Comment by ClydSpyd** [comment]
> Yes, you can do it after api has loaded, check here: https://github.com/google-map-react/google-map-react-examples/blob/master/src/examples/Main.js#L40

Hi Michael. 

Thanks so much for your response, but is the setBounds function not more for re-centering the map? What I need to obtain is the bounds information to pass to a new nearbySearch or even the new center point of the map upon dragend. Can this information be obtained with the setBounds function?

Cheers,
Dave

**Comment by itsmichaeldiego** [comment]
@ClydSpyd I showed you the way to access `map` and `maps` constant, with that you can do everything that you can do with normal google maps, so just look on how to do what you want to do in normal stackoverflow and you can tackle it from there

Makes sense?

**Comment by ClydSpyd** [comment]
@itsmichaeldiego yep, makes perfect sense. Thanks so much for your help!

**Comment by itsmichaeldiego** [comment]
@ClydSpyd Let me know if you can't find a way, but you should be able to access `map` and do `map.getBounds()`, you can set it to a variable.

**Comment by ClydSpyd** [comment]
@itsmichaeldiego I really appreciate your help, I have now managed to figure it out :) Thanks again!
