### ISSUE TITLE
Forgotten func variable definition in example.

### ISSUE THREAD

**Issue by redemptgtx** [google-map-react/google-map-react-examples#24]
https://github.com/google-map-react/google-map-react-examples/blob/f909321aaf4e451e2793e863597c247a0300814b/src/examples/Main.js#L69

We used places in this line but we forgot the define it in the arrow function, so it causes and error.

**Comment by itsmichaeldiego** [comment]
Hey, I don't see why it is an error for you? Places is defined a few lines above:
https://github.com/google-map-react/google-map-react-examples/blob/f909321aaf4e451e2793e863597c247a0300814b/src/examples/Main.js#L61
