### ISSUE TITLE
Loading librairies in a correct way

### ISSUE THREAD

**Issue by oussama-belkasmi** [google-map-react/google-map-react-examples#26]
Thank you for the examples they are very helpful to explain how to use the library.  
I tried the examples, in the main page when I click on _Default_ Element it works. The Map with markers is shown.  
 
When I click on _SearchBox_ Element in the main page, I get `TypeError: mapApi.places is undefined`.

**Comment by oussama-belkasmi** [comment]
The problem is due to two reasons :
1. The libraries are loaded in a not supported way. 
https://github.com/google-map-react/google-map-react-examples/blob/f909321aaf4e451e2793e863597c247a0300814b/src/examples/Searchbox.js#L48-L51

They will have to be loaded in this way 
``` 
  <GoogleMap
       ...
       bootstrapURLKeys={{key: process.env.REACT_APP_MAP_KEY}}
       placesLibrary={true}
       geometryLibrary={true}
       ... 
 >
      ...
  </GoogleMap>
```
2.   When the main page is loaded :
    1. If the _SearchBox_  is selected at first the app will show the map normally.
    2. If  element _Default_ was clicked before _SearchBox_ `TypeError: mapApi.places is undefined` will show instead.  This is due to the loading done only once in the app launch. For more information see [google-maps-api-loads-on-demand](https://github.com/google-map-react/google-map-react#google-maps-api-loads-on-demand).  
I didn't look for an elegant way to make this use case working. But using _browser refresh_  is an easy hack for this.


This issue is related to [google-map-react/issues/673](https://github.com/google-map-react/google-map-react/issues/673).

**Comment by itsmichaeldiego** [comment]
@oussama-belkasmi Thanks for this, we've updated the library now, let me now if it works for you, we're using `storybook` now
